services:
  postgres:
    image: postgis/postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
  api:
    build: ../api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres
      - mongo
      - redis
  worker:
    build: ../worker
    environment:
      TRANZY_API_KEY_PROD01: ${TRANZY_API_KEY_PROD01}
      TRANZY_API_KEY_PROD02: ${TRANZY_API_KEY_PROD02}
      TRANZY_API_KEY_PROD03: ${TRANZY_API_KEY_PROD03}
      ASPNETCORE_ENVIRONMENT: 'Production'
      MONGO__HOST: mongodb
      MONGO__PORT: 27017
      MONGO__DATABASE: UrbanWatchDB
      MONGO__USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO__PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    depends_on:
      - api
      - postgres
      - mongodb
      - redis

volumes:
  mongo_data:
  redis_data:
  pgdata:

  # ws:
  #   build: ../ws-server
  #   ports:
  #     - "6000:6000"
  #   environment:
  #     - REDIS_HOST=redis
