services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodata:/data/db
  worker:
    build: ./backend/worker
    environment:
      TRANZY_API_KEY_PROD01: ${TRANZY_API_KEY_PROD01}
      TRANZY_API_KEY_PROD02: ${TRANZY_API_KEY_PROD02}
      TRANZY_API_KEY_PROD03: ${TRANZY_API_KEY_PROD03}
      ASPNETCORE_ENVIRONMENT: 'Production'
      MONGO__HOST: mongodb
      MONGO__PORT: 27017
      MONGO__DATABASE: UrbanWatchDB
      MONGO__USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO__PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    depends_on:
      - mongodb

volumes:
  mongodata:
  # pgdata:

  # api:
  #   build: ./backend/api
  #   ports:
  #     - "5000:80"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - postgres
  #     - mongo
  #     - redis
  # ws:
  #   build: ./backend/ws-server
  #   ports:
  #     - "6000:6000"
  #   environment:
  #     - REDIS_HOST=redis

#   postgres:
#     image: postgis/postgis
#     environment:
#       - POSTGRES_USER=urban
#       - POSTGRES_PASSWORD=watch
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   redis:
#     image: redis
