services:
  worker:
    build: 
      context: ./backend/worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/worker:/app
    environment:
      - TRANZY_API_KEY_DEV01=${TRANZY_API_KEY_DEV01}
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "watch", "run", "--project", "src/UrbanWatch.Worker/UrbanWatch.Worker.csproj"]
